---
# Ansible Galaxy requirements
# Install: ansible-galaxy install -r requirements.yml

collections:
  - name: community.general
    version: ">=9.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: kewlfft.aur
    version: ">=0.9"
